"""dateTime

Revision ID: 72d45c646d9b
Revises: 9b0e45deb801
Create Date: 2024-07-02 15:39:05.601366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d45c646d9b'
down_revision: Union[str, None] = '9b0e45deb801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('date_create', sa.DateTime(), nullable=False))
    op.add_column('workout', sa.Column('date_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'date_update')
    op.drop_column('workout', 'date_create')
    # ### end Alembic commands ###
