"""altering

Revision ID: 9b0e45deb801
Revises: ade5e0038181
Create Date: 2024-07-02 12:46:37.060420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b0e45deb801'
down_revision: Union[str, None] = 'ade5e0038181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('max_weight', sa.Integer(), nullable=True))
    op.drop_column('workout', 'max_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('max_weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'max_weight')
    # ### end Alembic commands ###
