"""add_week

Revision ID: cf9a723f882b
Revises: 72d45c646d9b
Create Date: 2024-07-02 15:50:03.679035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf9a723f882b'
down_revision: Union[str, None] = '72d45c646d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('now_workout_week', sa.Integer(), nullable=True))
    op.add_column('workout', sa.Column('global_now_week', sa.Integer(), nullable=True))
    op.drop_column('workout', 'now_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('now_week', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('workout', 'global_now_week')
    op.drop_column('workout', 'now_workout_week')
    # ### end Alembic commands ###
