"""add_week_default2

Revision ID: e16ecd6dc2a4
Revises: eca8f4f85ebe
Create Date: 2024-07-03 01:32:15.983451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16ecd6dc2a4'
down_revision: Union[str, None] = 'eca8f4f85ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
